# Generated by Django 4.2 on 2024-07-23 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='type',
            field=models.CharField(choices=[('F', 'Fuego'), ('A', 'Agua'), ('E', 'Eléctrico'), ('T', 'Tierra'), ('P', 'Planta')], max_length=30),
        ),
    ]
